server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

spring:
  application:
    name: write-api
  datasource:
    url: ${WRITE_DATABASE_URL:jdbc:postgresql://localhost:5432/write_db}
    username: ${WRITE_DATABASE_USERNAME:cqrs}
    password: ${WRITE_DATABASE_PASSWORD:cqrs}
  jackson:
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      fail-fast: false
    properties:
      spring.json.add.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

cqrs:
  kafka:
    topic: ${KAFKA_TOPIC:product-events}
